- examples/avalanche_api_metrics.rs
- examples/aws_kms.rs
- examples/aws_s3.rs
- examples/scratch.rs
- src/avalanche/api/health.rs
- src/avalanche/api/metrics.rs
- src/aws/cloudformation.rs
- src/aws/cloudwatch.rs
- src/aws/ec2.rs
- src/aws/envelope.rs
- src/aws/kms.rs
- src/aws/s3.rs
- src/aws/sts.rs
- src/bin/avalanche-ops-aws/apply.rs
- src/bin/avalanche-ops-aws/delete.rs
- src/bin/avalanche-ops-aws/update_artifacts.rs
- src/bin/avalanched-aws/download_backup.rs
- src/bin/avalanched-aws/main.rs
- src/bin/avalanched-aws/run.rs
- src/bin/avalanched-aws/upload_backup.rs
- src/bin/dev-machine/apply.rs
- src/bin/dev-machine/delete.rs
- src/lib.rs
> *: make "avalanched" main async

- src/aws/cfn-templates/dev-machine/asg_amd64_al2.yaml
- src/aws/cfn-templates/dev-machine/asg_arm64_al2.yaml
- src/bin/avalanche-ops-aws/apply/mod.rs
- src/bin/dev-machine/apply/mod.rs
- src/bin/dev-machine/default_spec/mod.rs
- src/dev/mod.rs
- src/lib.rs
> *: dev machine with amd64

- Cargo.toml
> Cargo.toml: update "hyper" to 0.14.18

- avalanched-aws/src/run/mod.rs
> avalanched-aws/run: print out avalanche logs for liveness check failures

- avalanche-api/examples/eth.rs
- avalanche-api/examples/info.rs
- avalanche-api/examples/platform.rs
- avalanche-api/src/avm.rs
- avalanche-api/src/eth.rs
- avalanche-api/src/health.rs
- avalanche-api/src/info.rs
- avalanche-api/src/metrics.rs
- avalanche-api/src/platform.rs
- avalanche-types/src/api/avm.rs
- avalanche-types/src/api/health.rs
- avalanche-types/src/api/info.rs
- avalanche-types/src/api/platformvm.rs
- avalanche-types/src/avax.rs
- avalanche-types/src/avm/export.rs
- avalanche-types/src/avm/fx.rs
- avalanche-types/src/avm/import.rs
- avalanche-types/src/avm/tx.rs
- avalanche-types/src/ids.rs
- avalanche-types/src/platformvm/add_subnet_validator.rs
- avalanche-types/src/platformvm/add_validator.rs
- avalanche-types/src/platformvm/create_chain.rs
- avalanche-types/src/platformvm/create_subnet.rs
- avalanche-types/src/platformvm/export.rs
- avalanche-types/src/platformvm/import.rs
- avalanche-types/src/platformvm/mod.rs
- avalanche-types/src/secp256k1fx.rs
- utils/src/http.rs
- utils/src/prometheus.rs
- utils/src/rfc3339.rs
> *: implement serde se/de for "ids.rs"

- avalanche-types/src/api/avm.rs
- avalanche-types/src/api/info.rs
- avalanche-types/src/cert.rs
- avalanche-types/src/ids.rs
- avalanche-types/src/soft_key.rs
- subnetctl/src/add/validator.rs
- utils/src/secp256k1r.rs
> avalanche-types: use typed ID for everything

- avalanche-ops-aws/src/events/mod.rs
- avalanche-types/src/avax.rs
- avalanche-types/src/avm/export.rs
- avalanche-types/src/avm/import.rs
- avalanche-types/src/avm/tx.rs
- avalanche-types/src/codec.rs
- avalanche-types/src/formatting.rs
- avalanche-types/src/ids.rs
- avalanche-types/src/platformvm/add_subnet_validator.rs
- avalanche-types/src/platformvm/add_validator.rs
- avalanche-types/src/platformvm/create_chain.rs
- avalanche-types/src/platformvm/create_subnet.rs
- avalanche-types/src/platformvm/export.rs
- avalanche-types/src/platformvm/import.rs
- avalanche-types/src/platformvm/mod.rs
- avalanche-types/src/secp256k1fx.rs
- avalanche-types/src/soft_key.rs
- avalanched-aws/src/backup/mod.rs
- aws/examples/kms.rs
- aws/src/lib.rs
- subnetctl/src/add/validator.rs
- utils/src/cmp.rs
> avalanche-types: define ordering for sorting

- .rustfmt.nightly.toml
> rustfmt: add "normalize_doc_attributes"

- .github/workflows/test-and-release.yml
> workflows: upgrade to "actions/checkout@v3"

- avalanche-ops-aws/Cargo.toml
- avalanche-ops-aws/src/main.rs
- avalanched-aws/Cargo.toml
- avalanched-aws/src/main.rs
- dev-machine-aws/Cargo.toml
- dev-machine-aws/src/main.rs
> bins: add version flags

- avalanche-ops-aws/recipes-aws.md
- avalanche-types/Cargo.toml
- avalanche-types/src/avax.rs
- avalanche-types/src/ids.rs
> avalanche-types/ids.rs: use zerocopy

- avalanche-types/src/soft_key.rs
> soft_key.rs: use [u8] trait for "private_key_raw"

- avalanched-aws/Cargo.toml
- avalancheup-aws/Cargo.toml
- dev-machine-aws/Cargo.toml
> *: bump up "clap" dependencies to 3.1.10

- avalanche-types/Cargo.toml
- avalanched-aws/Cargo.toml
- avalancheup-aws/Cargo.toml
- dev-machine-aws/Cargo.toml
> *: bump up "clap" and "bitcoin" dependencies

- dev-machine-aws/cfn-templates/asg_amd64_al2.yaml
- dev-machine-aws/cfn-templates/asg_arm64_al2.yaml
> dev-machine: fix aws cli install script

- dev-machine-aws/cfn-templates/asg_amd64_ubuntu.yaml
- dev-machine-aws/cfn-templates/asg_arm64_al2.yaml
- dev-machine-aws/src/apply/mod.rs
- dev-machine-aws/src/default_spec/mod.rs
- dev-machine-aws/src/lib.rs
- dev-machine-aws/src/main.rs
> dev-machine: add amd64 with ubuntu

- avalanche-api/Cargo.toml
- avalanche-api/src/metrics.rs
- avalanche-types/Cargo.toml
- avalanched-aws/Cargo.toml
- avalanchego/Cargo.toml
- avalancheup-aws/Cargo.toml
- aws/Cargo.toml
- coreth/Cargo.toml
- dev-machine-aws/Cargo.toml
- subnet-evm/Cargo.toml
- utils/Cargo.toml
> Update dependencies (aws*, tokio, clap, serde*)

- avalanched-aws/src/run/mod.rs
- avalanchego/src/config.rs
- avalancheup-aws/cfn-templates/asg_amd64_ubuntu.yaml
- avalancheup-aws/recipes-aws.md
- avalancheup-aws/src/lib.rs
> *: replace "/avalanche-data" with "/data" for data dir paths

- avalanched-aws/Cargo.toml
- avalanchego/Cargo.toml
- avalancheup-aws/Cargo.toml
- scripts/tests.lint.sh
- scripts/tests.unused.sh
> *: fix CI, bump up avalanche-types dep

- avalanched-aws/Cargo.toml
- avalanchego/Cargo.toml
- avalancheup-aws/Cargo.toml
> *: update dependencies

- avalanchego/Cargo.toml
- bin/avalanched-aws/Cargo.toml
- bin/avalancheup-aws/Cargo.toml
- coreth/Cargo.toml
- subnet-evm/Cargo.toml
> *: bump up deps

- avalanchego/src/config.rs
- bin/avalanched-aws/Cargo.toml
- bin/avalanched-aws/src/run/mod.rs
- bin/avalancheup-aws/Cargo.toml
- bin/avalancheup-aws/cfn-templates/asg_amd64_ubuntu.yaml
- bin/avalancheup-aws/cfn-templates/ec2_instance_role.yaml
- bin/avalancheup-aws/recipes-aws.md
- bin/avalancheup-aws/src/apply/mod.rs
- bin/avalancheup-aws/src/default_spec/mod.rs
- bin/avalancheup-aws/src/delete/mod.rs
- bin/avalancheup-aws/src/lib.rs
- bin/avalancheup-aws/src/main.rs
- scripts/build.release.sh
> *: reuse EBS volumes per AZ

- bin/avalanched-aws/Cargo.toml
- bin/avalanched-aws/src/run/mod.rs
- bin/avalancheup-aws/Cargo.toml
- bin/avalancheup-aws/src/apply/mod.rs
- infra-aws/Cargo.toml
- infra-aws/examples/certs.rs
- infra-aws/src/certs/mod.rs
> *: use "infra-aws" cert manager

- bin/avalanched-aws/src/run/mod.rs
- infra-aws/src/telemetry/cloudwatch.rs
- infra-aws/src/telemetry/logs.rs
- infra-aws/src/telemetry/mod.rs
> *: modularized cloudwatch log config file

- bin/avalanched-aws/src/run/mod.rs
- infra-aws/Cargo.toml
- infra-aws/src/telemetry/metrics/avalanchego.rs
> infra-aws: modularize metrics fetch

- avalanchego/Cargo.toml
- bin/avalanched-aws/Cargo.toml
- bin/avalancheup-aws/Cargo.toml
- bin/avalancheup-aws/src/apply/mod.rs
- bin/avalancheup-aws/src/default_spec/mod.rs
- bin/avalancheup-aws/src/lib.rs
- coreth/Cargo.toml
- infra-aws/Cargo.toml
- subnet-evm/Cargo.toml
- subnet-evm/src/genesis.rs
> *: remove avalanche-utils dependencies

- bin/avalanched-aws/Cargo.toml
- bin/avalanched-aws/src/run/mod.rs
- bin/avalancheup-aws/cfn-templates/asg_amd64_ubuntu.yaml
> avalanched: tag EBS volume with Node Id

- .github/workflows/test-and-release.yml
- Cargo.toml
- bin/avalanched-aws/src/command.rs
- bin/avalancheup-aws/src/apply/mod.rs
- bin/staking-key-cert-s3-downloader/Cargo.toml
- bin/staking-key-cert-s3-downloader/src/command.rs
- bin/staking-key-cert-s3-downloader/src/flags.rs
- bin/staking-key-cert-s3-downloader/src/main.rs
- scripts/build.release.sh
> *: add "staking-key-cert-s3-downloader"

- bin/avalanched-aws/Cargo.toml
- bin/avalanched-aws/src/command.rs
- bin/avalancheup-aws/Cargo.toml
- bin/avalancheup-aws/cfn-templates/asg_amd64_ubuntu.yaml
- bin/avalancheup-aws/recipes-aws.md
- bin/avalancheup-aws/src/apply/mod.rs
- bin/avalancheup-aws/src/avalanched.rs
- bin/avalancheup-aws/src/aws.rs
- bin/avalancheup-aws/src/default_spec/mod.rs
- bin/avalancheup-aws/src/lib.rs
- bin/avalancheup-aws/src/main.rs
> avalanched: make flags configurable at avalancheup layer

- cdk/avalancheup-aws/.gitignore
- cdk/avalancheup-aws/.npmignore
- cdk/avalancheup-aws/README.md
- cdk/avalancheup-aws/bin/avalancheup-aws.ts
- cdk/avalancheup-aws/cdk.json
- cdk/avalancheup-aws/cfn-templates/avalancheup.yaml
- cdk/avalancheup-aws/jest.config.js
- cdk/avalancheup-aws/lib/avalancheup-aws-stack.ts
- cdk/avalancheup-aws/package-lock.json
- cdk/avalancheup-aws/package.json
- cdk/avalancheup-aws/test/avalancheup-aws.test.ts
- cdk/avalancheup-aws/tsconfig.json
> cdk: initial commit with CFN template (not working...)

- bin/avalanched-aws/Cargo.toml
- bin/avalancheup-aws/Cargo.toml
- bin/staking-key-cert-s3-downloader/Cargo.toml
- crates/avalanchego/Cargo.toml
- crates/coreth/Cargo.toml
- crates/subnet-evm/Cargo.toml
- infra-aws/Cargo.toml
> *: bump up aws deps

- bin/avalancheup-aws/recipes-aws.md
- bin/avalancheup-aws/src/apply/mod.rs
> apply: fix anchor node poll

- bin/avalanched-aws/Cargo.toml
- bin/avalancheup-aws/Cargo.toml
- bin/staking-key-cert-s3-downloader/Cargo.toml
- crates/avalanchego/Cargo.toml
- crates/coreth/Cargo.toml
- crates/subnet-evm/Cargo.toml
- infra-aws/Cargo.toml
> *: update deps

- bin/avalancheup-aws/recipes-aws.md
- crates/avalanchego/src/config.rs
- crates/coreth/src/config.rs
> *: use json log format by default

- crates/subnet-evm/src/genesis.rs
> subnet-evm: fix genesis

- bin/avalanched-aws/src/command.rs
- bin/avalancheup-aws/src/lib.rs
> *: make metrics regex configurable

- bin/avalanched-aws/src/command.rs
- bin/avalanched-aws/src/flags.rs
- bin/avalanched-aws/src/main.rs
- bin/avalancheup-aws/cfn-templates/asg_amd64_ubuntu.yaml
- bin/avalancheup-aws/recipes-aws.md
- bin/avalancheup-aws/src/avalanched.rs
- bin/avalancheup-aws/src/default_spec/mod.rs
- bin/avalancheup-aws/src/lib.rs
- bin/avalancheup-aws/src/main.rs
- cdk/avalancheup-aws/bin/avalancheup-aws.ts
> *: remove lite-mode, use skip/use default flags

- bin/avalancheup-aws/src/lib.rs
- crates/subnet-evm/src/genesis.rs
> subnet-evm: add fee manager config to genesis

- bin/avalancheup-aws/Cargo.toml
- bin/avalancheup-aws/artifacts/default.metrics.rules.yaml
> *: update default metrics, prometheus-manager to 0.0.11

- bin/avalanched-aws/Cargo.toml
- bin/avalanched-aws/src/command.rs
- bin/avalancheup-aws/src/apply/mod.rs
- bin/avalancheup-aws/src/lib.rs
- crates/avalanchego/src/config.rs
- crates/coreth/src/config.rs
- crates/subnet-evm/Cargo.toml
- crates/subnet-evm/src/config.rs
Fix https://github.com/ava-labs/avalanche-ops/issues/122
> *: support subnet-evm chain config with helpers

- bin/avalancheup-aws/Cargo.toml
- bin/avalancheup-aws/src/default_spec/mod.rs
- bin/avalancheup-aws/src/lib.rs
- bin/avalancheup-aws/src/main.rs
> *: support gas limit config with default-spec

- bin/avalanched-aws/src/command.rs
- crates/avalanchego/src/config.rs
- crates/coreth/src/config.rs
> *: do not overwrite coreth/avalanchego config on avalanched restarts

- bin/avalancheup-aws/cfn-templates/asg_amd64_ubuntu.yaml
- bin/avalancheup-aws/recipes-aws.md
- bin/avalancheup-aws/src/apply/mod.rs
- bin/avalancheup-aws/src/default_spec/mod.rs
- bin/avalancheup-aws/src/lib.rs
- bin/avalancheup-aws/src/main.rs
> *: make NLB creation optional (create by default)

- bin/avalancheup-aws/cfn-templates/asg_amd64_ubuntu.yaml
- bin/avalancheup-aws/src/apply/mod.rs
- bin/avalancheup-aws/src/default_spec/mod.rs
- bin/avalancheup-aws/src/lib.rs
- bin/avalancheup-aws/src/main.rs
> *: make volume size configurable

- bin/avalanched-aws/src/command.rs
- bin/avalancheup-aws/src/lib.rs
- crates/avalanchego/src/config.rs
- crates/coreth/src/config.rs
> *: set offline pruning data dir

- bin/avalanched-aws/Cargo.toml
- bin/avalanched-aws/src/command.rs
- bin/avalancheup-aws/Cargo.toml
- bin/avalancheup-aws/cfn-templates/ec2_instance_role.yaml
- bin/staking-key-cert-s3-downloader/Cargo.toml
- infra-aws/Cargo.toml
> *: set instance health before terminate, fix node health publish

- bin/avalanched-aws/src/command.rs
- bin/avalanched-aws/src/flags.rs
- bin/avalanched-aws/src/main.rs
- bin/avalancheup-aws/Cargo.toml
- bin/avalancheup-aws/recipes-aws.md
- bin/avalancheup-aws/src/avalanched.rs
- bin/avalancheup-aws/src/default_spec/mod.rs
- bin/avalancheup-aws/src/lib.rs
- bin/avalancheup-aws/src/main.rs
- cdk/avalancheup-aws/bin/avalancheup-aws.ts
- crates/avalanchego/Cargo.toml
- crates/coreth/Cargo.toml
- crates/subnet-evm/Cargo.toml
> *: disable periodic node info publish by default

- bin/avalanched-aws/Cargo.toml
- bin/avalancheup-aws/Cargo.toml
- bin/avalancheup-aws/src/lib.rs
- bin/staking-key-cert-s3-downloader/Cargo.toml
- crates/avalanchego/Cargo.toml
- crates/coreth/Cargo.toml
- crates/subnet-evm/Cargo.toml
- infra-aws/Cargo.toml
> *: update Rust 1.64, aws-manager, avalanche-types/sdk

- bin/avalanched-aws/Cargo.toml
- bin/avalanched-aws/src/command.rs
- bin/avalanched-aws/src/flags.rs
- bin/avalanched-aws/src/main.rs
- bin/avalancheup-aws/Cargo.toml
- bin/avalancheup-aws/src/apply/mod.rs
- bin/avalancheup-aws/src/default_spec/mod.rs
- bin/avalancheup-aws/src/delete/mod.rs
- bin/avalancheup-aws/src/main.rs
- bin/staking-key-cert-s3-downloader/Cargo.toml
- bin/staking-key-cert-s3-downloader/src/command.rs
- bin/staking-key-cert-s3-downloader/src/flags.rs
- bin/staking-key-cert-s3-downloader/src/main.rs
> *: migrate to clap 4

- bin/avalanched-aws/Cargo.toml
- bin/avalancheup-aws/Cargo.toml
- bin/blizzard-aws/Cargo.toml
- bin/blizzard-aws/src/command.rs
- bin/blizzardup-aws/Cargo.toml
- bin/blizzardup-aws/src/blizzard.rs
- bin/blizzardup-aws/src/lib.rs
- bin/blizzardup-aws/src/main.rs
- bin/blizzardup-aws/src/query/mod.rs
> [blizzard] add "query" subcommand + integrate with wallet for load testing

- bin/avalanched-aws/Cargo.toml
- bin/avalanched-aws/src/command.rs
- bin/avalancheup-aws/Cargo.toml
- bin/avalancheup-aws/src/lib.rs
- bin/blizzard-aws/Cargo.toml
- bin/blizzard-aws/src/command.rs
- bin/blizzardup-aws/Cargo.toml
- bin/blizzardup-aws/src/lib.rs
- bin/staking-key-cert-s3-downloader/Cargo.toml
- certs-manager/Cargo.toml
- certs-manager/src/lib.rs
- crates/avalanchego/Cargo.toml
> *: update avalanche-types/sdk to 0.52/0.0.52

- bin/avalanched-aws/Cargo.toml
- bin/avalancheup-aws/Cargo.toml
- bin/avalancheup-aws/cfn-templates/ec2_instance_role.yaml
- bin/avalancheup-aws/cfn-templates/ssm_doc_restart_node_whitelist_subnet.yaml
- bin/avalancheup-aws/src/apply/mod.rs
- bin/blizzard-aws/Cargo.toml
> *: fix ssm doc parameters, upgrade avalanche-sdk with polling

- bin/avalanched-aws/Cargo.toml
- bin/avalancheup-aws/Cargo.toml
- bin/avalancheup-aws/cfn-templates/asg_amd64_ubuntu.yaml
- bin/avalancheup-aws/src/apply/mod.rs
- bin/avalancheup-aws/src/lib.rs
- bin/blizzard-aws/Cargo.toml
- bin/blizzardup-aws/Cargo.toml
- bin/blizzardup-aws/cfn-templates/asg_amd64_ubuntu.yaml
- bin/blizzardup-aws/src/lib.rs
- bin/staking-key-cert-s3-downloader/Cargo.toml
- certs-manager/Cargo.toml
- certs-manager/examples/cert-manager.rs
For stable state in mainnet, xlarge is enough.
> *: use "xlarge" for default instance types

- bin/avalanched-aws/src/command.rs
- bin/avalancheup-aws/src/apply/mod.rs
- bin/avalancheup-aws/src/aws.rs
- bin/avalancheup-aws/src/default_spec/mod.rs
- bin/avalancheup-aws/src/delete/mod.rs
- bin/avalancheup-aws/src/lib.rs
> *: rename kms fields to more specific, combine test keys into one field

- bin/avalanched-aws/Cargo.toml
- bin/avalanched-aws/src/command.rs
- bin/avalancheup-aws/Cargo.toml
- bin/avalancheup-aws/src/apply/mod.rs
- bin/avalancheup-aws/src/lib.rs
- bin/blizzard-aws/Cargo.toml
- bin/blizzard-aws/src/command.rs
- bin/blizzardup-aws/Cargo.toml
- bin/blizzardup-aws/src/lib.rs
- bin/staking-key-cert-s3-downloader/Cargo.toml
- certs-manager/Cargo.toml
> *: use latest avalanche-types

- bin/avalanched-aws/src/command.rs
- bin/avalancheup-aws/cfn-templates/asg_amd64_ubuntu.yaml
- bin/avalancheup-aws/src/default_spec/mod.rs
- bin/avalancheup-aws/src/lib.rs
- bin/avalancheup-aws/src/main.rs
> *: default metrics fetch interval to 1-hour

- bin/avalanched-aws/Cargo.toml
- bin/avalancheup-aws/Cargo.toml
- bin/blizzard-aws/Cargo.toml
- bin/blizzardup-aws/Cargo.toml
- bin/staking-key-cert-s3-downloader/Cargo.toml
- certs-manager/Cargo.toml
> *: bump up rust, avalanche-types

- bin/avalanched-aws/Cargo.toml
- bin/avalanched-aws/src/command.rs
- bin/avalancheup-aws/Cargo.toml
- bin/avalancheup-aws/cfn-templates/asg_amd64_ubuntu.yaml
- bin/avalancheup-aws/recipes-aws.md
- bin/avalancheup-aws/src/apply/mod.rs
- bin/avalancheup-aws/src/default_spec/mod.rs
- bin/avalancheup-aws/src/delete/mod.rs
- bin/avalancheup-aws/src/lib.rs
- bin/avalancheup-aws/src/main.rs
- bin/blizzard-aws/Cargo.toml
- bin/blizzardup-aws/Cargo.toml
- bin/staking-key-cert-s3-downloader/Cargo.toml
- certs-manager/Cargo.toml
https://github.com/ava-labs/avalanche-ops/issues/134
> Support static ip with Elastic IP

- bin/avalancheup-aws/cfn-templates/asg_amd64_ubuntu.yaml
- bin/avalancheup-aws/recipes-aws.md
- bin/avalancheup-aws/src/apply/mod.rs
- bin/avalancheup-aws/src/default_spec/mod.rs
- bin/avalancheup-aws/src/delete/mod.rs
- bin/avalancheup-aws/src/main.rs
> *: rename "--delete-eips" to "--delete-elastic-ips"

- bin/avalanched-aws/Cargo.toml
- bin/avalanched-aws/src/command.rs
- bin/avalancheup-aws/Cargo.toml
- bin/avalancheup-aws/cfn-templates/ssm_doc_restart_node_chain_config.yaml
- bin/avalancheup-aws/recipes-aws.md
- bin/avalancheup-aws/src/apply/mod.rs
- bin/avalancheup-aws/src/aws.rs
- bin/avalancheup-aws/src/default_spec/mod.rs
- bin/avalancheup-aws/src/delete/mod.rs
- bin/avalancheup-aws/src/lib.rs
- bin/avalancheup-aws/src/main.rs
- bin/blizzard-aws/Cargo.toml
- bin/blizzardup-aws/Cargo.toml
- certs-manager/Cargo.toml
> avalancheup: remove whitelisted subnet flag

- bin/avalanched-aws/Cargo.toml
- bin/avalanched-aws/src/command.rs
- bin/avalancheup-aws/Cargo.toml
- bin/avalancheup-aws/cfn-templates/ssm_doc_restart_node_chain_config.yaml
- bin/avalancheup-aws/cfn-templates/ssm_doc_restart_node_whitelist_subnet.yaml
- bin/avalancheup-aws/recipes-aws.md
- bin/avalancheup-aws/src/apply/mod.rs
- bin/avalancheup-aws/src/default_spec/mod.rs
- bin/avalancheup-aws/src/lib.rs
- bin/avalancheup-aws/src/main.rs
- bin/blizzard-aws/Cargo.toml
- bin/blizzardup-aws/Cargo.toml
- certs-manager/Cargo.toml
> *: rename to "test_keys_with_funds", support subnet-evn subnet config

- bin/avalancheup-aws/src/apply/mod.rs
- bin/blizzard-aws/Cargo.toml
- bin/blizzard-aws/src/command.rs
- bin/blizzard-aws/src/evm.rs
- bin/blizzard-aws/src/main.rs
- bin/blizzard-aws/src/x.rs
- bin/blizzardup-aws/src/apply/mod.rs
- bin/blizzardup-aws/src/blizzard.rs
- bin/blizzardup-aws/src/default_spec/mod.rs
- bin/blizzardup-aws/src/lib.rs
- bin/blizzardup-aws/src/main.rs
- bin/blizzardup-aws/src/query/mod.rs
> blizzard, blizzardup: clean up

- bin/blizzard-aws/src/evm.rs
- bin/blizzard-aws/src/x.rs
> blizzard: cache signer nonces for EVM transactions

- bin/avalanched-aws/src/command.rs
- bin/avalancheup-aws/src/apply/mod.rs
- bin/avalancheup-aws/src/default_spec/mod.rs
- bin/avalancheup-aws/src/delete/mod.rs
- bin/avalancheup-aws/src/main.rs
- bin/avalancheup-aws/src/spec.rs
> avalancheup/d: support multiple subnets (wip)

- bin/avalanche-config/src/add_whitelist_subnet/mod.rs
- bin/avalanche-kms-signer-aws/src/create/mod.rs
- bin/avalanche-kms-signer-aws/src/delete/mod.rs
- bin/avalanche-kms-signer-aws/src/info/mod.rs
- bin/avalanched-aws/src/command.rs
- bin/avalanched-aws/src/main.rs
- bin/avalanched-aws/src/sync_subnet_evm_chain_config/mod.rs
- bin/avalanched-aws/src/sync_subnet_evm_subnet_config/mod.rs
- bin/avalancheup-aws/cfn-templates/ssm_doc_restart_node_chain_config.yaml
- bin/avalancheup-aws/cfn-templates/ssm_doc_restart_node_whitelist_subnet.yaml
- bin/avalancheup-aws/src/apply/mod.rs
- bin/avalancheup-aws/src/spec.rs
- bin/blizzard-aws/src/evm.rs
- bin/blizzard-aws/src/x.rs
- bin/blizzardup-aws/src/lib.rs
https://github.com/ava-labs/avalanche-ops/issues/204
> avalanched: sub-commands to write subnet/chain configurations

- bin/avalancheup-aws/Cargo.toml
- bin/avalancheup-aws/src/aws.rs
- bin/avalancheup-aws/src/default_spec/mod.rs
- bin/avalancheup-aws/src/delete/mod.rs
- bin/avalancheup-aws/src/spec.rs
For https://github.com/ava-labs/avalanche-ops/issues/160
> avalancheup: default-spec to create KMS CMKs

- bin/avalanche-config/Cargo.toml
- bin/avalanche-kms-signer-aws/Cargo.toml
- bin/avalanched-aws/Cargo.toml
- bin/avalancheup-aws/Cargo.toml
- bin/avalancheup-aws/src/apply/mod.rs
- bin/blizzard-aws/Cargo.toml
- bin/blizzardup-aws/Cargo.toml
- certs-manager/Cargo.toml
> xsvm: fix genesis bytes installation

- bin/avalanche-config/Cargo.toml
- bin/avalanche-kms-signer-aws/Cargo.toml
- bin/avalanched-aws/Cargo.toml
- bin/avalancheup-aws/Cargo.toml
- bin/blizzard-aws/Cargo.toml
- bin/blizzardup-aws/Cargo.toml
- bin/staking-key-cert-s3-downloader/Cargo.toml
- certs-manager/Cargo.toml
> *: update dep

- bin/avalanche-config/Cargo.toml
- bin/avalanche-config/README.md
- bin/avalanche-config/src/add_tracked_subnet/mod.rs
- bin/avalanche-config/src/main.rs
- bin/avalanche-kms-signer-aws/Cargo.toml
- bin/avalanched-aws/Cargo.toml
- bin/avalanched-aws/src/command.rs
- bin/avalancheup-aws/Cargo.toml
- bin/avalancheup-aws/cfn-templates/ssm_doc_restart_node_chain_config_subnet_evm.yaml
- bin/avalancheup-aws/cfn-templates/ssm_doc_restart_node_tracked_subnet_subnet_evm.yaml
- bin/avalancheup-aws/cfn-templates/ssm_doc_restart_node_tracked_subnet_xsvm.yaml
- bin/avalancheup-aws/example-aws.md
- bin/avalancheup-aws/src/apply/mod.rs
- bin/avalancheup-aws/src/aws.rs
- bin/avalancheup-aws/src/delete/mod.rs
- bin/avalancheup-aws/src/spec.rs
- bin/blizzard-aws/Cargo.toml
- bin/blizzardup-aws/Cargo.toml
- bin/staking-key-cert-s3-downloader/Cargo.toml
- certs-manager/Cargo.toml
> *: rename "whitelist" to "track" subnets

- bin/avalancheup-aws/cfn-templates/asg_amd64_ubuntu.yaml
- bin/avalancheup-aws/src/apply/mod.rs
- bin/avalancheup-aws/src/aws.rs
> cfn: share launch template for anchor + non-anchor nodes

- bin/avalancheup-aws/cfn-templates/asg_amd64_ubuntu.yaml
- bin/avalancheup-aws/src/apply/mod.rs
- bin/avalancheup-aws/src/aws.rs
- bin/avalancheup-aws/src/default_spec/mod.rs
- bin/avalancheup-aws/src/main.rs
- bin/avalancheup-aws/src/spec.rs
> *: single ASG for each node

- avalanche-config-installer/src/github.rs
- bin/avalanched-aws/Cargo.toml
- bin/avalanched-aws/src/command.rs
- bin/avalanched-aws/src/install/mod.rs
- bin/avalanched-aws/src/main.rs
- bin/avalancheup-aws/Cargo.toml
- bin/avalancheup-aws/cfn-templates/asg_ubuntu.yaml
- bin/avalancheup-aws/cfn-templates/vpc.yaml
- bin/avalancheup-aws/src/apply/mod.rs
- bin/avalancheup-aws/src/default_spec/mod.rs
- bin/avalancheup-aws/src/main.rs
- bin/avalancheup-aws/src/spec.rs
- bin/blizzardup-aws/cfn-templates/asg_ubuntu.yaml
- bin/blizzardup-aws/src/apply/mod.rs
- bin/blizzardup-aws/src/lib.rs
https://github.com/ava-labs/avalanche-ops/issues/250
> Support arm64

- avalanche-kms/Cargo.toml
- avalanche-kms/src/create/mod.rs
- avalanche-kms/src/delete/mod.rs
- avalanche-kms/src/info/mod.rs
- avalanche-ops/Cargo.toml
- avalanched-aws/Cargo.toml
- avalanched-aws/src/agent/mod.rs
- avalanched-aws/src/install_artifacts/mod.rs
- avalanched-aws/src/install_chain/mod.rs
- avalanched-aws/src/install_subnet/mod.rs
- avalancheup-aws/Cargo.toml
- avalancheup-aws/src/apply/mod.rs
- avalancheup-aws/src/delete/mod.rs
- avalancheup-aws/src/install_subnet_chain/mod.rs
- blizzard-aws/Cargo.toml
- blizzard-aws/src/command.rs
- blizzardup-aws/Cargo.toml
- blizzardup-aws/src/apply/mod.rs
- blizzardup-aws/src/delete/mod.rs
- staking-key-cert-s3-downloader/Cargo.toml
- staking-key-cert-s3-downloader/src/command.rs
To work around https://github.com/awslabs/aws-sdk-rust/issues/611
> Operational timeout

- avalanche-kms/Cargo.toml
- avalanche-ops/Cargo.toml
- avalanched-aws/Cargo.toml
- avalancheup-aws/Cargo.toml
- avalancheup-aws/src/install_subnet_chain/mod.rs
- blizzard-aws/Cargo.toml
- blizzardup-aws/Cargo.toml
- staking-key-cert-s3-downloader/Cargo.toml
- staking-signer-key-s3-downloader/Cargo.toml
ref. https://github.com/ava-labs/avalanche-ops/issues/306
> 0.4.1-rc.4: bump up deps + parallelize add validators

- README.md
More details on logging in successfully for new users.
> docs: Add details on avalancheup authentication

- CODEOWNERS
> dev: Add CODEOWNERS

- avalanche-kms/src/create/mod.rs
- avalanche-kms/src/evm_transfer_from_hotkey/mod.rs
- avalanche-kms/src/main.rs
- avalanche-ops/src/aws/spec.rs
- avalanched-aws/src/agent/mod.rs
- avalanched-aws/src/install_artifacts/mod.rs
- avalanched-aws/src/main.rs
- avalancheup-aws/src/add_primary_network_validators/mod.rs
- avalancheup-aws/src/apply/mod.rs
- avalancheup-aws/src/delete/mod.rs
- avalancheup-aws/src/endpoints/mod.rs
- avalancheup-aws/src/install_subnet_chain/mod.rs
- avalancheup-aws/src/main.rs
- blizzard-aws/src/command.rs
- blizzard-aws/src/evm.rs
- blizzardup-aws/src/apply/mod.rs
- blizzardup-aws/src/lib.rs
- blizzardup-aws/src/main.rs
- devnet-faucet/src/command.rs
Lints the existing codebase with clippy.
> lint: Run clippy --fix

- avalancheup-aws/src/apply/dev_machine.rs
- avalancheup-aws/src/apply/mod.rs
Removes unnecessary code and updates existing functions to be used.
> fix: Update dev machine functionality to match simplified feature design

- avalancheup-aws/src/apply/mod.rs
https://github.com/ava-labs/avalanche-ops/issues/384
> Fix SSH command blocking

- avalanche-ops/src/aws/spec.rs
- avalanche-ops/src/dev-machines/cfn-templates/asg_ubuntu.yaml
- avalancheup-aws/src/apply/mod.rs
PR to support launching a dev box in each region specified by the user automatically. 
> Support dev machines in each region

- avalanche-ops/src/aws/cfn-templates/asg_ubuntu.yaml
- avalanche-ops/src/dev-machines/cfn-templates/asg_ubuntu.yaml
- avalancheup-aws/src/apply/mod.rs
> cfn: Update ec2 key ref to be conditional

- avalanche-kms/Cargo.toml
- avalanche-ops/Cargo.toml
- avalanched-aws/Cargo.toml
- avalancheup-aws/Cargo.toml
- avalancheup-aws/src/apply/mod.rs
- blizzard-aws/Cargo.toml
- blizzardup-aws/Cargo.toml
- staking-key-cert-s3-downloader/Cargo.toml
- staking-signer-key-s3-downloader/Cargo.toml
https://github.com/ava-labs/avalanche-ops/issues/419
> *: retries put_object for s3 api calls

- LICENSE
Updates the license to match hypersdk
> docs: Update Ecosystem License to v1.1

- avalanche-ops/src/aws/spec.rs
- avalancheup-aws/src/apply/mod.rs
- avalancheup-aws/src/default_spec/mod.rs
- avalancheup-aws/src/main.rs
For https://github.com/ava-labs/avalanche-ops/issues/390.
> avalancheup-aws: add vm-install flags (not implemented yet)

- avalanche-kms/Cargo.toml
- avalanche-ops/Cargo.toml
- avalanched-aws/Cargo.toml
- avalancheup-aws/Cargo.toml
- avalancheup-aws/src/apply/mod.rs
- blizzard-aws/Cargo.toml
- blizzardup-aws/Cargo.toml
- devnet-faucet/Cargo.toml
- staking-key-cert-s3-downloader/Cargo.toml
- staking-signer-key-s3-downloader/Cargo.toml
Address https://github.com/ava-labs/avalanche-ops/issues/390.
Replace https://github.com/ava-labs/avalanche-ops/pull/427.
> feat(avalancheup): automatic subnet installation in apply

- avalancheup-aws/src/apply/mod.rs
> fix: Surface error when upload artifacts to s3

- avalanche-kms/Cargo.toml
- avalanche-ops/Cargo.toml
- avalanched-aws/Cargo.toml
- avalancheup-aws/Cargo.toml
- blizzard-aws/Cargo.toml
- blizzardup-aws/Cargo.toml
- devnet-faucet/Cargo.toml
- staking-key-cert-s3-downloader/Cargo.toml
- staking-signer-key-s3-downloader/Cargo.toml
Pre 1.0 release. Still ironing out s3 upload issues therefore alpha.
> *: Update to 1.0.0-alpha.1

- avalanche-kms/Cargo.toml
- avalanche-ops/Cargo.toml
- avalanched-aws/Cargo.toml
- avalancheup-aws/Cargo.toml
- blizzard-aws/Cargo.toml
- blizzardup-aws/Cargo.toml
- devnet-faucet/Cargo.toml
- staking-key-cert-s3-downloader/Cargo.toml
> *: Bump avalanche-types to v0.0.405
